site_name: Egzamin Ósmoklasisty
site_description: Repozytorium materiałów i opracowań egzaminacyjnych.

nav:
  - Start: index.md
  - Arkusze PDF: pdfs.md
  - Notatki (JP): notatki-jezyk-polski.md
  - Notatki (MAT): notatki-matematyka.md
  - Notatki (ANG): notatki-jezyk-angielski.md

theme:
  name: material
  language: pl
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Tryb ciemny
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Tryb jasny
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - footnotes

plugins:
  - search
  - git-revision-date-localized:
      type: date
      enable_parallel_processing: false
